IMAGEW=imagew

all: \
	appicon-20.png \
	appicon-20@2x.png \
	appicon-20@3x.png \
	appicon-29.png \
	appicon-29@2x.png \
	appicon-29@3x.png \
	appicon-40.png \
	appicon-40@2x.png \
	appicon-40@3x.png \
	appicon-60@2x.png \
	appicon-60@3x.png \
	appicon-76.png \
	appicon-76@2x.png \
	appicon-83-5@2x.png \
	appicon-1024.png 

appicon-20.png:simra.png
	$(IMAGEW) -w 20 -h 20 $< $@

appicon-20@2x.png:simra.png
	$(IMAGEW) -w 40 -h 40 $< $@

appicon-20@3x.png:simra.png
	$(IMAGEW) -w 60 -h 60 $< $@

appicon-29.png:simra.png
	$(IMAGEW) -w 29 -h 29 $< $@

appicon-29@2x.png:simra.png
	$(IMAGEW) -w 58 -h 58 $< $@

appicon-29@3x.png:simra.png
	$(IMAGEW) -w 87 -h 87 $< $@

appicon-40.png:simra.png
	$(IMAGEW) -w 40 -h 40 $< $@

appicon-40@2x.png:simra.png
	$(IMAGEW) -w 80 -h 80 $< $@

appicon-40@3x.png:simra.png
	$(IMAGEW) -w 120 -h 120 $< $@

appicon-60@2x.png:simra.png
	$(IMAGEW) -w 120 -h 120 $< $@

appicon-60@3x.png:simra.png
	$(IMAGEW) -w 180 -h 180 $< $@

appicon-76.png:simra.png
	$(IMAGEW) -w 76 -h 76 $< $@

appicon-76@2x.png:simra.png
	$(IMAGEW) -w 152 -h 152 $< $@

appicon-83-5@2x.png:simra.png
	$(IMAGEW) -w 167 -h 167 $< $@

appicon-1024.png:simra.png
	$(IMAGEW) -w 1024 -h 1024 $< $@
